# Generated by Django 4.1.1 on 2022-12-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
